stages:
  dataset:
    cmd: python3 mlflow/dataset.py
    params:
      - dataset.split
    deps:
      - mlflow/dataset.py
      - data/raw
    outs:
      - data/interim

  features:
    cmd: python3 mlflow/features.py
    deps:
      - mlflow/features.py
      - data/interim
    outs:
      - data/processed
